"""add site_settings for emission factor and declared compliance inputs

Revision ID: 5c035ed51515
Revises: 14e1d12725f9
Create Date: 2026-09-21 19:11:32.164040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c035ed51515'
down_revision: Union[str, None] = '14e1d12725f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    site_settings = op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_emission_factor_kg_per_kwh', sa.Float(), nullable=False),
    sa.Column('emission_factor_source', sa.String(), nullable=False),
    sa.Column('installed_it_capacity_kw', sa.Float(), nullable=True),
    sa.Column('renewable_energy_factor', sa.Float(), nullable=True),
    sa.Column('energy_reuse_factor', sa.Float(), nullable=True),
    sa.Column('telemetry_simulated', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_settings_id'), 'site_settings', ['id'], unique=False)

    # Seed the single settings row (id=1) so the table is usable straight
    # after `alembic upgrade head`. Values match compliance.DEFAULT_*.
    op.bulk_insert(site_settings, [{
        'id': 1,
        'grid_emission_factor_kg_per_kwh': 0.710,
        'emission_factor_source': 'CEA CO2 Baseline Database v21.0, FY2024-25 all-India weighted average (0.710 tCO2/MWh)',
        'telemetry_simulated': True,
    }])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_settings_id'), table_name='site_settings')
    op.drop_table('site_settings')
    # ### end Alembic commands ###
